import { StyleSheet } from 'react-native';
import Colors from '../../Assets/Style/Color';

const CreateQuoteStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.black_bg_Theme,
  },
  contentContainer: {
    flex: 1,
    marginHorizontal: 20,
    marginBottom: 10,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    margin: 10,
    textAlign: 'center',
    color: Colors.blue_theme_Color,
  },
  checkboxGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 16,
    marginBottom: 8,
    backgroundColor: Colors.blue_theme_Color,
    padding: 10,
    width: '45%',
    borderRadius: 10,
  },
  CheckBoxLabel: {
    color: '#fff',
    fontWeight: 'bold',
  },
  label: {
    fontSize: 14,
    color: Colors.white_text_color,
    marginBottom: 4,
    marginVertical: 5,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputLocation: {
    borderWidth: 0.7,
    borderColor: '#7E7C7CFF',
    borderRadius: 5,
    color: Colors.white_text_color,
    width: '65%',
    height: 50,
    paddingHorizontal: 10,
    marginRight: 5,
    marginBottom: 5,
    backgroundColor: Colors.black_bg_Theme,
  },
  fetchLocation: {
    borderWidth: 0.7,
    borderRadius: 5,
    width: '33%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: Colors.blue_theme_Color,
    marginBottom: 5,
  },
  inputWithIcon: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0.7,
    borderColor: '#7E7C7CFF',
    borderRadius: 5,
    height: 50,
    paddingHorizontal: 10,
    marginBottom: 8,
    backgroundColor: Colors.black_bg_Theme,
    marginRight: 5,
  },
  button: {
    marginTop: 16,
    backgroundColor: Colors.blue_theme_Color,
    borderRadius: 10,
    marginBottom: 80,
  },
  selectimageCont: {
    flex: 1,
    flexDirection: 'row',
    borderWidth: 0.7,
    borderColor: '#7E7C7CFF',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    backgroundColor: Colors.black_bg_Theme,
    borderRadius: 5,
  },
  showImg: {
    borderWidth: 0.5,
    width: 50,
    height: 40,
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    padding: 5,
    backgroundColor: '#ffffff',
  },
  calendarModal: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    position: 'absolute',
    top: '30%',
    left: '10%',
    right: '10%',
    zIndex: 1, // Ensure the modal content is above the background
  },
  closeModalButton: {
    marginTop: 20,
    backgroundColor: 'red',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  modalBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Semi-transparent black
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 0, // Ensure the background is below the modal content
  },
  closeModalButton: {
    backgroundColor: Colors.blue_theme_Color,
    padding: 10,
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 10,
  },
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  dropdownWrapper: {
    flex: 1,
    position: 'relative',
  },
  storeFrontdropdown: {
    flex: 1,
    position: 'absolute',
    top: 80,
    left: 0,
    right: 0,
    backgroundColor: Colors.blue_theme_Color,
    borderWidth: 0.5,
    borderColor: '#ccc',
    borderRadius: 5,
    zIndex: 1,
    elevation: 1,
    height: 'auto',
    maxHeight: 250,
    overflow: 'scroll',
  },
  storeFrontdropdown1: {
    flex: 1,
    position: 'absolute',
    top: 50,
    left: 0,
    right: 0,
    backgroundColor: Colors.blue_theme_Color,
    borderWidth: 0.5,
    borderColor: '#ccc',
    borderRadius: 5,
    zIndex: 1,
    elevation: 1,
    height: 'auto',
    maxHeight: 250,
    overflow: 'scroll',
  },
  dropdown: {
    flex: 1,
    position: 'absolute',
    top: 50,
    left: 0,
    right: 0,
    backgroundColor: Colors.blue_theme_Color,
    // borderWidth: 0.5,
    // borderColor: '#ccc',
    borderRadius: 5,
    zIndex: 1,
    elevation: 1,
    height: 'auto',
    maxHeight: 280,
    overflow: 'scroll',
  },
  residentialJobDropdown: {
    flex: 1,
    position: 'absolute',
    top: 50,
    left: 0,
    right: 0,
    backgroundColor: Colors.blue_theme_Color,
    borderWidth: 0.5,
    borderColor: '#ccc',
    borderRadius: 5,
    zIndex: 1,
    elevation: 1,
    height: 'auto',
    maxHeight: 250,
    overflow: 'scroll',
  },
  CustomerDropdown: {
    flex: 1,
    top: -6,
    left: 0,
    right: 0,
    backgroundColor: Colors.blue_theme_Color,
    // borderWidth: 0.5,
    // borderColor: '#ccc',
    borderRadius: 5,
    zIndex: 1,
    elevation: 1,
    maxHeight: 280,
    overflow: 'scroll',
  },
  dropdownItem: {
    padding: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: '#ccc',
  },
  dropdownText: {
    fontSize: 16,
    color: '#fff',
  },
  dropdownText1: {
    fontSize: 16,
    color: '#fff',
    textAlign: 'center',
  },
  deleteButton: {
    padding: 5,
  },
  input: {
    flex: 1,
    height: 50,
    paddingHorizontal: 10,
    backgroundColor: Colors.black_bg_Theme,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    borderWidth: 0.7,
    borderColor: '#ccc',
    color: Colors.white_text_color,
    textAlign: 'center',
  },
  inputforToolTip: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    borderWidth: 0.7,
    borderColor: '#ccc',
    borderRadius: 5,
    height: 50,
    marginRight: 8,
    backgroundColor: Colors.black_bg_Theme,
    color: Colors.white_text_color,
  },
  inputPrice: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 0.6,
    borderWidth: 0.7,
    borderColor: '#ccc',
    borderRadius: 5,
    height: 50,
    marginRight: 8,
    backgroundColor: Colors.black_bg_Theme,
  },
  hoursMinContainer: {
    flexDirection: 'row',
    width: 100,
    borderWidth: 0.8,
    borderRadius: 5,
    marginRight: 8,
  },
  inputForHours: {
    justifyContent: 'center',
    flex: 1,
    height: 50,
    backgroundColor: Colors.black_bg_Theme,
    borderWidth: 0.7,
    borderColor: '#ccc',
    borderRadius: 5,
  },
  inputForMin: {
    justifyContent: 'center',
    flex: 1,
    height: 50,
    borderWidth: 0.7,
    borderColor: '#ccc',
    borderRadius: 5,
    backgroundColor: Colors.black_bg_Theme,
  },
  swmsBlock: {
    backgroundColor: Colors.grey_bg_Color,
    marginBottom: 10,
    padding: 5,
    borderRadius: 5,
  },
  swmsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  addButton: { alignSelf: 'center', marginVertical: 5 },
  image: { width: 40, height: 50, borderRadius: 8 },
  imageRowContainer: {
    flexDirection: 'row', // This makes the images display horizontally
    flexWrap: 'wrap', // Allows wrapping of images if they exceed the container width
    marginTop: 10,
  },
  imageContainer: {
    position: 'relative', // To position the delete button over the image
  },
  imageBottom: {
    width: 50, // Width of each image
    height: 50, // Height of each image
    borderRadius: 8, // Optional, to make the images rounded
  },
  iconHoverOnImageRow: {
    position: 'absolute',
    top: -10,
    right: 20,
    backgroundColor: '#fff', // Optional background for the delete button
    borderRadius: 50, // Make the delete button round
    padding: 5,
  },
  iconHoverOnImage: {
    position: 'absolute',
    top: -3,
    right: -5,
    backgroundColor: '#fff', // Optional background for the delete button
    borderRadius: 50, // Make the delete button round
    padding: 5,
  },
  iconContainer: {
    justifyContent: 'center',
    marginRight: 5,
  },
  iconContainerPrice: {
    justifyContent: 'center',
    marginLeft: 10,
  },
  tooltipWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Semi-transparent background
  },
  tooltipContainer: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 8,
    width: 300,
    alignItems: 'center',
  },
  tooltipText: {
    color: '#424242FF',
    fontSize: 16,
    marginBottom: 20,
  },
  suggestionList: {
    position: 'absolute',
    top: 50, // Adjust based on your input field's position
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ccc',
    maxHeight: 200,
    zIndex: 1,
  },
  suggestionText: {
    padding: 10,
    fontSize: 16,
    color: '#333',
  },
  loaderContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 9999,
  },
  setUpText: {
    textAlign: 'center',
    color: Colors.white_text_color,
  },
  setUpContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  requiredText: {
    color: 'red',
    fontSize: 16,
  },
  crossIcon: {
    marginRight: 5,
  },
  cancelButton: {
    padding: 5,
    backgroundColor: Colors.grey_bg_Color,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    borderWidth: 0.3,
    borderColor: '#ccc',
  },
  cancelText: {
    textAlign: 'center',
    color: Colors.white_text_color,
    fontWeight: 'bold',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: Colors.black_bg_Theme,
  },
});
export default CreateQuoteStyle;
