import { StyleSheet } from "react-native";
import Colors from "../../Assets/Style/Color";

const ExpenseStyle = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.black_bg_Theme,
    },
    contentContainer: {
      flex: 1,
      paddingHorizontal: 10,
      marginBottom: 10,
    },
    mainContainer: {
      //  backgroundColor : 'white',
      //  padding : 10,
      //  elevation : 2,
      //  borderRadius : 10
    },
    rowWrapper: {
      marginBottom: 10,
      paddingTop: 10,
      backgroundColor: Colors.grey_bg_Color,
      borderRadius: 5,
      shadowColor: '#000',
      shadowOpacity: 0.2,
      shadowOffset: {width: 0, height: 4},
      elevation: 6,
      borderWidth: 0.1,
      borderColor: '#ccc',
      padding: 10,
    },
    title: {
      fontSize: 18,
      fontWeight: 'bold',
      marginVertical: 10,
      // textAlign: 'center',
      color: Colors.blue_theme_Color,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      // marginBottom: 10,
    },
    input: {
      flex: 1,
      // borderWidth: 1,
      borderColor: '#ccc',
      borderRadius: 8,
      height: 50,
      paddingHorizontal: 10,
      backgroundColor: '#ffffff',
    },
    inputWithIcon: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      marginBottom: 10,
      paddingVertical: 5,
      flex: 1,
      backgroundColor: Colors.black_bg_Theme,
      borderRadius: 5,
      shadowColor: '#000',
      shadowOpacity: 0.2,
      shadowOffset: {width: 0, height: 4},
      elevation: 6,
      borderWidth: 1.2,
      borderColor: '#6E6D6DFF',
    },
    checkboxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 10,
      backgroundColor: Colors.blue_theme_Color,
      borderRadius: 8,
      // marginBottom: 10,
      flex: 1,
    },
    checkboxLabel: {
      color: '#ffffff',
      fontWeight: 'bold',
      marginLeft: 5,
    },
    textArea: {
      // borderWidth: 0.3,
      borderColor: '#ccc',
      borderRadius: 8,
      height: 80,
      paddingHorizontal: 10,
      backgroundColor: Colors.black_bg_Theme,
      marginBottom: 10,
      textAlignVertical: 'top',
    },
    cameraIcon: {
      paddingHorizontal: 10,
    },
    deleteButton: {
      paddingHorizontal: 10,
    },
    buttonRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      // marginTop: 20,
    },
    button: {
      flex: 1,
      // marginHorizontal: 5,
      padding: 10,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.blue_theme_Color,
      borderRadius: 5,
    },
    submittedButton: {
      flex: 1,
      marginHorizontal: 5,
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.green_color,
      borderRadius: 8,
    },
    buttonText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    image: {
      width: 40,
      height: 50,
      borderRadius: 8,
      // marginTop: 10,
      marginLeft: 10,
    },
    label: {
      fontSize: 14,
      color: Colors.white_text_color,
      marginBottom: 4,
    },
    dropdownWrapper: {
      flex: 1,
      position: 'relative',
    },
    dropdown: {
      position: 'absolute',
      top: 73,
      left: 0,
      right: 0,
      backgroundColor: Colors.blue_theme_Color,
      borderWidth: 0.1,
      borderColor: '#ccc',
      borderRadius: 5,
      zIndex: 1,
      elevation: 1,
      height: 'auto',
      maxHeight: 200,
    },
    dropdownItem: {
      padding: 10,
      borderBottomWidth: 0.5,
      borderBottomColor: '#ccc',
    },
    dropdownText: {
      fontSize: 16,
      color: '#fff',
    },
    iconMargin: {
      marginHorizontal: 5,
    },
    iconCOntainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      top: 5,
    },
    iconHoverOnImage: {
      bottom: 40,
      left: 30,
      position: 'absolute',
      backgroundColor: Colors.blue_theme_Color,
      borderRadius: 20,
    },
    iconHoverOnImage1: {
      bottom: 40,
      position: 'absolute',
      backgroundColor: Colors.blue_theme_Color,
      borderRadius: 20,
    },
    calendarModal: {
      position: 'absolute',
      top: '30%',
      left: '5%',
      width: '90%',
      backgroundColor: 'white',
      padding: 10,
      borderRadius: 10,
      elevation: 5,
    },
    closeModalButton: {
      backgroundColor: Colors.blue_theme_Color,
      padding: 10,
      alignItems: 'center',
      borderRadius: 5,
      marginTop: 10,
    },
    modalBackground: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)', // Semi-transparent background
    },
    modalContainer: {
      backgroundColor: '#FFF',
      padding: 20,
      borderRadius: 10,
      alignItems: 'center',
      width: 350,
    },
    modalText: {
      fontSize: 18,
      marginBottom: 20,
    },
    button1: {
      backgroundColor: Colors.blue_theme_Color,
      width: 120,
      padding: 10,
      margin: 5,
      borderRadius: 5,
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 0,
    },
    resetButton: {
      backgroundColor: Colors.blue_theme_Color,
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: 5,
    },
    resetButtonText: {
      color: 'white',
      fontWeight: 'bold',
    },
    Buttoncontainer: {
      marginVertical: 10,
    },
    selectFileButton: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.black_bg_Theme,
      paddingVertical: 12,
      borderRadius: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 5,
      borderWidth: 2,
      borderStyle: 'dashed',
      borderColor: Colors.granite_Gray_color,
    },
    icon: {
      marginRight: 10,
    },
    selectedFile: {
      marginTop: 10,
      fontSize: 14,
      color:Colors.gray_html_color,
      textAlign: 'center',
    },
    noResultContainer: {
      paddingVertical: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    noResultText: {
      color: Colors.white_text_color,
      fontSize: 12,
      fontStyle: 'italic',
    },

    noResultContainer: {
      paddingVertical: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    
    noResultText: {
      color: Colors.white_text_color,
      fontSize: 14,
      fontStyle: 'italic',
    },
    
    
  });
  export default ExpenseStyle;