import { StyleSheet } from "react-native";
import Colors from "../../Assets/Style/Color";

const PaidInvoiceStyle = StyleSheet.create({
    container: {
      flex: 1,
      padding: 10,
      backgroundColor: Colors.grey_bg_Color, 
      borderRadius: 10,
      shadowColor: '#000',
      shadowOpacity: 0.2,
      shadowOffset: { width: 0, height: 4 },
      elevation: 6, 
      marginBottom: 20,
      borderWidth: 1, 
      borderColor: '#333', 
      marginTop : 10,
      height : 650
    },
    container1: {
      flex: 1,
      padding: 10,
      backgroundColor: Colors.grey_bg_Color, 
      borderRadius: 10,
      shadowColor: '#000',
      shadowOpacity: 0.2,
      shadowOffset: { width: 0, height: 4 },
      elevation: 6, 
      marginBottom: 20,
      borderWidth: 1, 
      borderColor: '#333', 
      marginTop : 10,
    },
    summaryContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    summaryItem: {
      flex: 1,
      alignItems: 'center',
      marginHorizontal: 5,
    },
    summaryLabel: {
      fontSize: 16,
      color: Colors.white_text_color,
      fontWeight: 'bold',
      marginBottom: 5,
    },
    summaryValue: {
      fontSize: 16,
      color: Colors.blue_theme_Color,
      fontWeight: 'bold',
      paddingHorizontal: 15,
      paddingVertical: 5,
      textAlign: 'center',
      backgroundColor: Colors.black_bg_Theme, 
      borderRadius: 10,
      shadowColor: '#000',
      shadowOpacity: 0.2,
      shadowOffset: { width: 0, height: 4 },
      elevation: 6, 
      borderWidth: 1, 
      borderColor: '#333', 
    },
    headerRow: {
      flexDirection: 'row',
      backgroundColor: Colors.blue_theme_Color,
      padding: 10,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerText: {
      flex: 1,
      color: 'white',
      fontWeight: 'bold',
      fontSize: 14,
      textAlign: 'center',
    },
    row: {
      flexDirection: 'row',
      padding: 10,
      marginVertical: 5,
      backgroundColor: Colors.black_bg_Theme, 
      borderRadius: 10,
      shadowColor: '#000',
      shadowOpacity: 0.2,
      shadowOffset: { width: 0, height: 4 },
      elevation: 6, 
      borderWidth: 1, 
      borderColor: '#333', 
    },
    cell: {
      flex: 1,
      fontSize: 14,
      color: Colors.white_text_color,
      textAlign: 'center',
    },
    listContainer: {
      marginTop: 10,
    },
    noDataContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.grey_bg_Color,
      borderRadius: 10,
      padding: 20,
      borderWidth: 1,
      borderColor: '#333',
      marginTop: 10,
    },
    noDataText: {
      fontSize: 18,
      color: Colors.white_text_color,
      fontWeight: 'bold',
      textAlign: 'center',
    }
  });

export default PaidInvoiceStyle;