import { StyleSheet } from "react-native";
import Colors from "../../Assets/Style/Color";

const QuotesStyle = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.black_bg_Theme,
    },
    contentContainer: {
      flex: 1,
      paddingHorizontal: 10,
    },
    dateRangeContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 7,
      marginLeft: 10,
    },
    refreshIcon: {
      marginTop: 40,
      marginRight: 10,
    },
    FilterIcon: {
      position: 'absolute',
      zIndex: 1000,
      right : 20,
      bottom : 50,
      justifyContent : 'center',
      alignItems : 'center',
      alignSelf : 'center',
      flexDirection : 'row',
      borderWidth : 1,
      borderColor : Colors.pink_theme_color,
      backgroundColor: Colors.grey_bg_Color,
      paddingHorizontal : 12,
      paddingVertical : 8,
      borderRadius : 30,
      margin : 5,
    },
    FilterIcon1: {
      position: 'absolute',
      zIndex: 1000,
      top: 85,
      left : 18,
    },
    dateRangeText: {
      fontSize: 15,
      fontWeight: 'bold',
      color: Colors.blue_theme_Color,
    },
    dateInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    dateInput: {
      width: 70,
      height: 40,
      backgroundColor: Colors.grey_bg_Color,
      borderRadius: 5,
      elevation: 5,
      borderWidth: 0.2,
      borderColor: Colors.white_text_color,
      textAlign: 'center',
      fontSize: 12,
      padding: 10,
      color: Colors.white_text_color,
    },
    dateInput1: {
      backgroundColor: Colors.grey_bg_Color,
      borderRadius: 5,
      elevation: 5,
      borderWidth: 0.2,
      borderColor: Colors.white_text_color,
      fontSize: 12,
      paddingVertical: 10,
      width: 95,
      height: 40,
    },
    toText: {
      fontSize: 15,
      fontWeight: 'bold',
      marginLeft: 8,
      color: Colors.blue_theme_Color,
    },
    summaryRow: {
      flexDirection: 'row',
      marginBottom: 10,
    },
    summaryBox: {
      flex: 1,
      alignItems: 'center',
    },
    summaryText: {
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderWidth: 1,
      borderColor: Colors.blue_theme_Color,
      marginHorizontal: 5,
      elevation: 2,
      backgroundColor: Colors.grey_bg_Color,
      borderRadius: 5,
      marginVertical: 5,
      fontSize: 12,
      color: Colors.white_text_color,
    },
    label: {
      fontSize: 14,
      fontWeight: 'bold',
      color: Colors.Neon_Blue_Theme_Color,
      textAlign: 'center',
    },
    filterLabel : {
      fontSize: 14,
      fontWeight: 'bold',
      color: Colors.white_text_color,
      textAlign: 'center',
      marginLeft : 5,
    },
    labelTop: {
      fontSize: 14,
      fontWeight: 'bold',
      color: Colors.Neon_Blue_Theme_Color,
      textAlign: 'center',
      marginBlock: 5,
    },
    card: {
      backgroundColor: Colors.grey_bg_Color,
      borderRadius: 10,
      shadowColor: '#000',
      shadowOpacity: 0.2,
      shadowOffset: {width: 0, height: 4},
      elevation: 6,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: '#333',
    },
    cardRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
      cardRowNew: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    cardItem: {
      flex: 1,
      alignItems: 'center',
    },
    cardItem1: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.blue_theme_Color,
      borderRadius: 5,
      marginRight : 5
    },
    disabledButton: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'red',
      borderRadius: 5,
      marginRight : 5
    },
    invoicedButton : {
      flex : 1,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.green_color,
      borderRadius: 5,
      marginRight : 5,
      marginLeft : 25,
    },
    cardLabel: {
      fontWeight: 'bold',
      fontSize: 16,
      marginBottom: 5,
      color: Colors.Neon_Blue_Theme_Color,
    },
    cardLabel1: {
      fontWeight: 'bold',
      fontSize: 14,
      marginBottom: 5,
      color: Colors.bgwhite,
      marginRight: 5,
      textAlign: 'center',
    },
    cardValue: {
      fontSize: 14,
      color: Colors.white_text_color,
    },
    cardValue1: {
      fontSize: 14,
      color: Colors.black_text_color,
    },
    modalContainer: {
      flex: 1,
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
      backgroundColor: Colors.white_text_color,
      padding: 20,
      borderRadius: 10,
      width: '80%',
    },
    listContainer: {
      flex: 1, 
    },
    downloadIcon: {
      paddingRight: 10, 
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
      flex: 0, 
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: Colors.theme_background_dark,
      textAlign: 'center',
    },
    noDataText: {
      textAlign: 'center',
      fontSize: 18,
      color: Colors.theme_background_dark,
      marginTop: 20,
      textAlign: 'center',
      color: Colors.white_text_color,
    },
    checkboxContainer: {
      marginBottom: 5,
      flexDirection: 'row',
    },
    checkboxItem: {
      flexDirection: 'row',
      alignItems: 'center',
      // marginBottom: 10,
      flex: 1,
    },
    Button: {
      backgroundColor: Colors.blue_theme_Color,
      flex: 1,
      margin: 5,
      padding: 10,
      borderRadius: 2,
    },
    Button1: {
      backgroundColor: Colors.pink_theme_color,
      flex: 1,
      margin: 5,
      padding: 10,
      borderRadius: 2,
    },
    Button2: {
      backgroundColor: Colors.green_color,
      flex: 1,
      margin: 5,
      padding: 10,
      borderRadius: 2,
    },
    modalButtonText: {
      textAlign: 'center',
      color: Colors.white_text_color,
      fontWeight: 'bold',
    },
    statusText: {
      fontSize: 16,
      textAlign: 'center',
      color: Colors.gray_text_color,
      fontWeight: 'bold',
    },
    imgContainer: {
      alignItems: 'center',
      marginBottom: 10,
    },
    img: {
      width: 300,
      height: 200,
      borderRadius: 10,
      resizeMode: 'contain',
    },
    smallImageContainer: {
      flexDirection: 'row',
      marginBottom: 20,
    },
    smallImage: {
      width: 60,
      height: 60,
      marginRight: 10,
      borderRadius: 5,
    },
    datetext: {
      color: Colors.white_text_color,
      textAlign: 'center',
    },
    reloadButtonContainer : {
      justifyContent : 'center',
      alignItems : 'center',
      alignSelf : 'center',
      width : '30%',
      padding : 5,
      borderRadius : 5
    },
    reloadText : {
      textAlign : 'center',
      color : Colors.white_text_color
    },
    loaderContainer: {
      position: 'absolute', 
      top: 0, 
      left: 0, 
      right: 0, 
      bottom: 0, 
      justifyContent: 'center', 
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      zIndex: 9999,
    },
    checkboxContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
    },
    checkboxRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    checkboxLabel: {
      color: Colors.white_text_color,
    },
    locationContainer : {
      flexDirection: 'row',
      alignItems: 'center',
    },
    locationText : {
      color: Colors.white_text_color,
      marginLeft : 2,
      fontSize : 10
    },
    searchContainer : {
      marginLeft: 30,
    }
  });

export default QuotesStyle;
  