import {StyleSheet} from 'react-native';
import Colors from '../../Assets/Style/Color';

const ScheduleListStyle = StyleSheet.create({
  card: {
    // backgroundColor: '#EEEEEEFF',
    padding: 10,
    marginHorizontal: 15,
    marginVertical: 10,
    backgroundColor: Colors.grey_bg_Color,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 4},
    elevation: 6,
    borderWidth: 1,
    borderColor: '#333',
  },
  card1: {
    // backgroundColor: '#EEEEEEFF',
    padding: 10,
    marginHorizontal: 15,
    marginVertical: 10,
    backgroundColor: Colors.grey_bg_Color,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 4},
    elevation: 6,
    borderWidth: 1,
    borderColor: '#333',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'sans-serif',
    marginBottom: 10,
    color: Colors.blue_theme_Color,
    marginHorizontal: 5,
  },
  valueLabel: {
    marginVertical: 5,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  label: {
    fontSize: 14,
    fontWeight: 'bold',
    marginVertical: 2,
    marginHorizontal: 5,
    color: Colors.white_text_color,
  },
  input: {
    flex: 1,
    backgroundColor: Colors.black_bg_Theme,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 4},
    elevation: 6,
    borderWidth: 0.4,
    borderColor: '#ccc',
    padding: 10,
  },
  inputForNotes: {
    textAlign: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.black_bg_Theme,
    borderRadius: 5,
    elevation: 6,
    borderWidth: 0.4,
    borderColor: '#ccc',
    padding: 10,
    height: 80,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  button: {
    flex: 1,
    backgroundColor: Colors.theme_background_dark,
    padding: 10,
    alignItems: 'center',
    borderRadius: 4,
    marginHorizontal: 5,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  checkboxContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  checkbox: {
    backgroundColor: Colors.black_bg_Theme,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 4},
    elevation: 6,
    borderWidth: 0.4,
    borderColor: '#ccc',
    padding: 10,
    alignItems: 'center',
  },
  imgContainer: {
    flex: 1,
    borderWidth: 0.5,
    borderColor: '#ccc',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: Colors.black_bg_Theme,
  },
  image: {
    width: '100%',
    height: 100,
  },
  titleContainer: {
    paddingVertical: 5,
  },
  titleMain: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'sans-serif',
    color: Colors.blue_theme_Color,
  },
  rowUp: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  labelUp: {
    marginRight: 10,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'sans-serif',
    color: Colors.white_text_color,
  },
  notvalue: {
    fontSize: 14,
    marginVertical: 2,
    marginHorizontal: 5,
    color: Colors.gray_text_color,
    textAlign: 'center',
  },
  value: {
    fontWeight: 'bold',
    textAlign: 'center',
    borderWidth: 0.5,
    width: 100,
    borderColor: '#ccc',
    borderRadius: 5,
    fontFamily: 'sans-serif',
    color: Colors.white_text_color,
  },
  inputRemainder: {
    borderWidth: 0.4,
    borderColor: Colors.theme_background_dark,
    borderRadius: 4,
    padding: 10,
    marginHorizontal: 5,
    marginTop: 23,
    flex: 0.5,
    height: 42,
    backgroundColor: Colors.blue_theme_Color,
  },
  inputRemainderRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageContainer: {
    flex: 1, // Ensure the container takes up equal space in the row
    borderWidth: 0.4,
    borderColor: '#ccc',
    borderRadius: 4,
    marginTop: 5,
    padding: 10,
    backgroundColor: Colors.black_bg_Theme,
  },
  noJobsContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  noJobText: {
    color: 'white',
    textAlign: 'center',
  },
  animation: {
    width: '100%',
    height: 120,
    // backgroundColor : Colors.black_bg_Theme,
  },
});
export default ScheduleListStyle;
